CamposDealer/Controllers/VendasController.cs
using CamposDealer.Models;
using CamposDealer.Repositorio;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace CamposDealer.Controllers
{
    public class VendasController : Controller
    {
        private readonly IVendaRepositorio _vendaRepositorio;
        private readonly IClienteRepositorio _clienteRepositorio;
        private readonly IProdutoRepositorio _produtoRepositorio;

        public VendasController(IVendaRepositorio vendaRepositorio, IClienteRepositorio clienteRepositorio, IProdutoRepositorio produtoRepositorio)
        {
            _vendaRepositorio = vendaRepositorio;
            _clienteRepositorio = clienteRepositorio;
            _produtoRepositorio = produtoRepositorio;
        }

        public IActionResult Index()
        {
            List<VendaModel> vendas = _vendaRepositorio.BuscarTodos();

            foreach (var venda in vendas)
            {
                venda.Cliente = _clienteRepositorio.ListarPorId(venda.IdCliente);
                venda.Produto = _produtoRepositorio.ListarPorId(venda.IdProduto);
            }

            return View(vendas);
        }


        public IActionResult Criar()
        {
            ViewBag.Clientes = _clienteRepositorio.BuscarTodos();
            ViewBag.Produtos = _produtoRepositorio.BuscarTodos();
            return View();
        }

        public IActionResult Editar(int id)
        {
            ViewBag.Clientes = _clienteRepositorio.BuscarTodos();
            ViewBag.Produtos = _produtoRepositorio.BuscarTodos(); 
            VendaModel venda = _vendaRepositorio.ListarPorId(id);
            return View(venda);
        }

        public IActionResult DeleteConfirmation(int id)
        {
            VendaModel venda = _vendaRepositorio.ListarPorId(id);
            return View(venda);
        }

        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagado = _vendaRepositorio.Apagar(id);
                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Cliente apagado com sucesso";

                }
                else
                {
                    TempData["MensagemErro"] = "Não conseguimos apagar o cliente ";

                }
                return RedirectToAction("Index");

            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Erro ao atualizar cliente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Criar(VendaModel venda)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _vendaRepositorio.Adicionar(venda);

                    ProdutoModel produto = _produtoRepositorio.ListarPorId(venda.IdProduto);

                    venda.VlrUnitarioVenda = (decimal)produto.ValorUnitario;

                    venda.VlrTotalVenda = (decimal)(venda.QtdVenda * (float)produto.ValorUnitario);

                    _vendaRepositorio.Atualizar(venda);

                    TempData["MensagemSucesso"] = "Venda cadastrada com sucesso";
                    return RedirectToAction("Index");
                }

                ViewBag.Clientes = _clienteRepositorio.BuscarTodos();
                ViewBag.Produtos = _produtoRepositorio.BuscarTodos();
                return View(venda);
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Erro ao cadastrar venda, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }





        [HttpPost]
        public IActionResult Alterar(VendaModel venda)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ProdutoModel produto = _produtoRepositorio.ListarPorId(venda.IdProduto);

                    venda.VlrUnitarioVenda = (decimal)produto.ValorUnitario;

                    venda.QtdVenda = venda.QtdVenda;

                    venda.VlrTotalVenda = (decimal)(venda.QtdVenda * produto.ValorUnitario);

                    _vendaRepositorio.Atualizar(venda);
                    TempData["MensagemSucesso"] = "Venda alterada com sucesso";
                    return RedirectToAction("Index");
                }

                ViewBag.Clientes = _clienteRepositorio.BuscarTodos();
                ViewBag.Produtos = _produtoRepositorio.BuscarTodos();
                return View("Editar", venda);
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Erro ao atualizar venda, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }


        public IActionResult ApagarConfirmacao(int id)
        {
            VendaModel Vendas = _vendaRepositorio.ListarPorId(id);
            return View(Vendas);
        }
    }
}

CamposDealer/Views/Vendas/ApagarConfirmacao.cshtml
@model VendaModel
@{
    ViewData["Title"] = "Confirmação de apagar a venda";
}
<div class="text-center">
    <h3>Realmente deseja apagar a venda número (@Model.IdVenda)? </h3>


</div>

<a class="btn btn-primary btn-block" role="button" asp-controller="Vendas" asp-action="Index">Cancelar Exclusão</a>
<a class="btn btn-danger btn-block" role="button" asp-controller="Vendas" asp-action="Apagar" asp-route-id="@Model.IdVenda">Confirmar Exclusão</a>

CamposDealer/Views/Vendas/Criar.cshtml
@model VendaModel
@{
    ViewData["Title"] = "Criar Venda";
}

<div class="text-center">
    <h1 class="display-4">Criar Venda</h1>
</div>

<form asp-controller="Vendas" asp-action="Criar" method="post">

    <div class="form-group">
        <label for="idCliente">Cliente</label>
        <select asp-for="IdCliente" class="form-control">
            <option value="">Selecione um cliente</option>
            @foreach (var cliente in ViewBag.Clientes)
            {
                <option value="@cliente.Id">@cliente.Nome</option>
            }
        </select>
        @Html.ValidationMessageFor(x => x.IdCliente)
    </div>

    <div class="form-group">
        <label for="idProduto">Produto</label>
        <select asp-for="IdProduto" class="form-control">
            <option value="">Selecione um produto</option>
            @foreach (var produto in ViewBag.Produtos)
            {
                <option value="@produto.Id">@produto.Descricao</option>
            }
        </select>
        @Html.ValidationMessageFor(x => x.IdProduto)
    </div>

    <div class="form-group">
        <label for="qtdVenda">Quantidade</label>
        <input type="number" asp-for="QtdVenda" class="form-control" placeholder="Digite a quantidade">
        @Html.ValidationMessageFor(x => x.QtdVenda)
    </div>

    <div class="form-group">
        <label for="dthVenda">Data da Venda</label>
        <input type="datetime-local" asp-for="DthVenda" class="form-control">
        @Html.ValidationMessageFor(x => x.DthVenda)
    </div>

    <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
    <a class="btn btn-secondary btn-block" asp-controller="Vendas" asp-action="Index" role="button">Voltar</a>
</form>

CamposDealer/Views/Vendas/Editar.cshtml
@model VendaModel
@{
    ViewData["Title"] = "Editar Venda";
}

<div class="text-center">
    <h1 class="display-4">Editar Venda</h1>
</div>

<form asp-controller="Vendas" asp-action="Alterar" method="post">

    <input type="hidden" asp-for="IdVenda" />

    <div class="form-group">
        <label for="idCliente">Cliente</label>
        <select asp-for="IdCliente" class="form-control">
            <option value="">Selecione um cliente</option>
            @foreach (var cliente in ViewBag.Clientes)
            {
                <option value="@cliente.Id">@cliente.Nome</option>
            }
        </select>
        @Html.ValidationMessageFor(x => x.IdCliente)
    </div>

    <div class="form-group">
        <label for="idProduto">Produto</label>
        <select asp-for="IdProduto" class="form-control">
            <option value="">Selecione um produto</option>
            @foreach (var produto in ViewBag.Produtos)
            {
                <option value="@produto.Id">@produto.Descricao</option>
            }
        </select>
        @Html.ValidationMessageFor(x => x.IdProduto)
    </div>

    <div class="form-group">
        <label for="qtdVenda">Quantidade</label>
        <input type="number" asp-for="QtdVenda" class="form-control" placeholder="Digite a quantidade">
        @Html.ValidationMessageFor(x => x.QtdVenda)
    </div>

    <div class="form-group">
        <label for="dthVenda">Data da Venda</label>
        <input type="datetime-local" asp-for="DthVenda" class="form-control">
        @Html.ValidationMessageFor(x => x.DthVenda)
    </div>

    <button type="submit" class="btn btn-primary btn-block">Editar</button>
    <a class="btn btn-secondary btn-block" asp-controller="Vendas" asp-action="Index" role="button">Voltar</a>
</form>

CamposDealer/Views/Vendas/Index.cshtml
@model List<VendaModel>

<h1>Listagem de Vendas</h1>
<br />
<div class="text-center">
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Vendas" asp-action="Criar">Adicionar nova venda</a>
    </div>
    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>

    }
    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>

    }
    <br />

    <table class="table" id="table1">
    <thead>
        <tr>
            <th>Id</th>
            <th>Cliente</th>
            <th>Produto</th>
            <th>Quantidade</th>
            <th>Valor Unitário</th>
            <th>Data da Venda</th>
            <th>Valor Total</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var venda in Model)
        {
            <tr>
                <td>@venda.IdVenda</td>
                <td>@venda.Cliente.Nome</td>
                <td>@venda.Produto.Descricao</td>
                <td>@venda.QtdVenda</td>
                <td>@venda.VlrUnitarioVenda</td>
                <td>@venda.DthVenda</td>
                <td>@venda.VlrTotalVenda</td>
                <td>
                        <a role="button" class="btn btn-primary" asp-route-id="@venda.IdVenda" asp-controller="Vendas" asp-action="Editar">Editar</a>
                        <a role="button" class="btn btn-danger" asp-route-id="@venda.IdVenda" asp-controller="Vendas" asp-action="ApagarConfirmacao">Apagar</a>

                </td>
            </tr>
        }
    </tbody>
</table>